<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDzhb2j7\catwalkFrontastic_Catwalk_AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDzhb2j7/catwalkFrontastic_Catwalk_AppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDzhb2j7.legacy');

    return;
}

if (!\class_exists(catwalkFrontastic_Catwalk_AppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDzhb2j7\catwalkFrontastic_Catwalk_AppKernelProdContainer::class, catwalkFrontastic_Catwalk_AppKernelProdContainer::class, false);
}

return new \ContainerDzhb2j7\catwalkFrontastic_Catwalk_AppKernelProdContainer([
    'container.build_hash' => 'Dzhb2j7',
    'container.build_id' => '2be81c7b',
    'container.build_time' => 1601962814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDzhb2j7');
