// This file is autogenerated – run `ant apidocs` to update it

export interface PageMatcherContext {
     entity?: null | any;
     categoryId?: null | string;
     productId?: null | string;
     contentId?: null | string;
     search?: null | string;
     cart?: null | any;
     checkout?: null | any;
     checkoutFinished?: null | any;
     orderId?: null | string;
     account?: null | any;
     accountForgotPassword?: null | any;
     accountConfirm?: null | any;
     accountProfile?: null | any;
     accountAddresses?: null | any;
     accountOrders?: null | any;
     accountWishlists?: null | any;
     accountVouchers?: null | any;
     error?: null | any;
}
