---
name: "Frontastic Catwalk"
source: src
target: docs
autoloader: vendor/autoload.php
nameSpace: "\\Frontastic\\Catwalk"
typeScript:
  target: src/js/types.ts
  nameSpace:
    search: '(^\\(?:([A-Za-z]+?)(?:Api)?Bundle\\)?Domain\\)'
    replace: '\1\\'
  includes:
    "Frontastic\\Common": '@frontastic/common/src/js/types'
  indent: 4
files:
 - php/ApiCoreBundle/Domain/*.php
 - php/ApiCoreBundle/Domain/*/*.php
 - php/FrontendBundle/Domain/*.php
 - php/FrontendBundle/Domain/*/*.php
 - php/FrontendBundle/Routing/ObjectRouter/ProductRouter.php
reference:
 - ../../libraries/common/src/php/*Bundle/Domain/*.php
 - ../../libraries/common/src/php/*Bundle/Domain/*/*.php
 - ../../libraries/common/src/php/*Bundle/Domain/*/*/*.php
