// This file is autogenerated – run `ant apidocs` to update it

import {
    Configuration as FrontendConfiguration,
} from '..'

export interface Configuration extends FrontendConfiguration {
     size?: any;
}
