// This file is autogenerated – run `ant apidocs` to update it

export interface PageFolderTreeValue extends PageFolderValue {
     children?: PageFolderTreeValue[];
     requestedDepth?: null | number;
}

export interface PageFolderValue {
     pageFolderId?: string;
     name?: string;
     configuration?: any;
     hasLivePage?: boolean;
     _urls?: any;
     /**
      * The url for the current locale
      */
     _url?: string;
}
