// This file is autogenerated – run `ant apidocs` to update it

export interface LinkReferenceValue extends ReferenceValue {
    type?: string
    link?: null | string
    target?: string
}

export interface PageFolderReferenceValue extends ReferenceValue {
    type?: string
    pageFolder?: PageFolderValue
}

export interface PageFolderTreeValue extends PageFolderValue {
    children?: PageFolderTreeValue[]
    requestedDepth?: null | number
}

export interface PageFolderValue {
    pageFolderId?: string
    name?: string
    configuration?: any
    _urls?: any
}

export interface ReferenceValue {
    type?: string
    openInNewWindow?: boolean
}
