<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* FrontasticCatwalkApiCoreBundle:App:dataObject.php.twig */
class __TwigTemplate_55306f9520962345f341a8aaf07e8292e4b9a666c7b7a0b06f5abe36a7ea2a75 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 1
        echo "<?php

namespace Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\App;

use Doctrine\\ORM\\Mapping as ORM;
use Kore\\DataObject\\DataObject;

/**
 * Class: ";
        // line 9
        echo twig_escape_filter($this->env, ($context["className"] ?? null), "html", null, true);
        echo "
 *
 * This file has been autogenerated. Any changes to
 * this file will be overwritten again. Do NOT change
 * anything in this file.
 *
 * @ORM\\Entity(repositoryClass=\"Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\DataRepository\")
 * @ORM\\Table(
    name=\"";
        // line 17
        echo twig_escape_filter($this->env, ($context["tableName"] ?? null), "html", null, true);
        echo "\",
    indexes={
        @ORM\\Index(name=\"idx_sequence\", columns={\"d_locale\", \"d_sequence\"}),
    ";
        // line 20
        $context['_parent'] = $context;
        $context['_seq'] = twig_ensure_traversable(($context["indexes"] ?? null));
        foreach ($context['_seq'] as $context["_key"] => $context["index"]) {
            // line 21
            echo "        @ORM\\Index(
            name=\"c_idx_";
            // line 22
            echo twig_escape_filter($this->env, twig_lower_filter($this->env, twig_get_attribute($this->env, $this->source, $context["index"], "name", [], "any", false, false, false, 22)), "html", null, true);
            echo "\",
            columns={
                \"d_locale\", ";
            // line 24
            $context['_parent'] = $context;
            $context['_seq'] = twig_ensure_traversable(twig_get_attribute($this->env, $this->source, $context["index"], "fields", [], "any", false, false, false, 24));
            foreach ($context['_seq'] as $context["_key"] => $context["field"]) {
                echo "\"d_";
                echo twig_escape_filter($this->env, twig_lower_filter($this->env, $context["field"]), "html", null, true);
                echo "\", ";
            }
            $_parent = $context['_parent'];
            unset($context['_seq'], $context['_iterated'], $context['_key'], $context['field'], $context['_parent'], $context['loop']);
            $context = array_intersect_key($context, $_parent) + $_parent;
            // line 25
            echo "            }
        ),
    ";
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['_key'], $context['index'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 28
        echo "    })
 * @SuppressWarnings(\"TooManyFields\") This is a generated DTO.
 */
class ";
        // line 31
        echo twig_escape_filter($this->env, ($context["className"] ?? null), "html", null, true);
        echo " extends DataObject
{
    /**
     * @ORM\\Id
     * @ORM\\Column(name=\"d_locale\", type=\"string\")
     * @var string
     */
    public \$locale;

    /**
     * @ORM\\Id
     * @ORM\\Column(name=\"d_id\", type=\"string\")
     * @var string
     */
    public \$dataId;

    /**
     * @ORM\\Column(name=\"d_sequence\", type=\"string\")
     * @var string
     */
    public \$sequence;

    /**
     * @ORM\\Column(name=\"d_is_deleted\", type=\"boolean\", options={\"default\" = false})
     * @var bool
     */
    public \$isDeleted = false;

";
        // line 59
        $context['_parent'] = $context;
        $context['_seq'] = twig_ensure_traversable(($context["properties"] ?? null));
        $context['loop'] = [
          'parent' => $context['_parent'],
          'index0' => 0,
          'index'  => 1,
          'first'  => true,
        ];
        if (is_array($context['_seq']) || (is_object($context['_seq']) && $context['_seq'] instanceof \Countable)) {
            $length = count($context['_seq']);
            $context['loop']['revindex0'] = $length - 1;
            $context['loop']['revindex'] = $length;
            $context['loop']['length'] = $length;
            $context['loop']['last'] = 1 === $length;
        }
        foreach ($context['_seq'] as $context["property"] => $context["type"]) {
            // line 60
            echo "    /**
     * @ORM\\Column(name=\"d_";
            // line 61
            echo twig_escape_filter($this->env, twig_lower_filter($this->env, $context["property"]), "html", null, true);
            echo "\", type=\"";
            echo twig_escape_filter($this->env, ((twig_get_attribute($this->env, $this->source, ($context["doctrineTypeMap"] ?? null), $context["type"], [], "array", true, true, false, 61)) ? (_twig_default_filter((($__internal_f607aeef2c31a95a7bf963452dff024ffaeb6aafbe4603f9ca3bec57be8633f4 = ($context["doctrineTypeMap"] ?? null)) && is_array($__internal_f607aeef2c31a95a7bf963452dff024ffaeb6aafbe4603f9ca3bec57be8633f4) || $__internal_f607aeef2c31a95a7bf963452dff024ffaeb6aafbe4603f9ca3bec57be8633f4 instanceof ArrayAccess ? ($__internal_f607aeef2c31a95a7bf963452dff024ffaeb6aafbe4603f9ca3bec57be8633f4[$context["type"]] ?? null) : null), "text")) : ("text")), "html", null, true);
            echo "\", nullable=true)
     * @var ";
            // line 62
            echo twig_escape_filter($this->env, ((twig_get_attribute($this->env, $this->source, ($context["doctrineTypeMap"] ?? null), $context["type"], [], "array", true, true, false, 62)) ? (_twig_default_filter((($__internal_62824350bc4502ee19dbc2e99fc6bdd3bd90e7d8dd6e72f42c35efd048542144 = ($context["doctrineTypeMap"] ?? null)) && is_array($__internal_62824350bc4502ee19dbc2e99fc6bdd3bd90e7d8dd6e72f42c35efd048542144) || $__internal_62824350bc4502ee19dbc2e99fc6bdd3bd90e7d8dd6e72f42c35efd048542144 instanceof ArrayAccess ? ($__internal_62824350bc4502ee19dbc2e99fc6bdd3bd90e7d8dd6e72f42c35efd048542144[$context["type"]] ?? null) : null), "text")) : ("text")), "html", null, true);
            echo "
     */
    public \$";
            // line 64
            echo twig_escape_filter($this->env, $context["property"], "html", null, true);
            echo ";
";
            // line 65
            if ( !twig_get_attribute($this->env, $this->source, $context["loop"], "last", [], "any", false, false, false, 65)) {
                // line 66
                echo "
";
            }
            ++$context['loop']['index0'];
            ++$context['loop']['index'];
            $context['loop']['first'] = false;
            if (isset($context['loop']['length'])) {
                --$context['loop']['revindex0'];
                --$context['loop']['revindex'];
                $context['loop']['last'] = 0 === $context['loop']['revindex0'];
            }
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['property'], $context['type'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 69
        echo "}
";
    }

    public function getTemplateName()
    {
        return "FrontasticCatwalkApiCoreBundle:App:dataObject.php.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  184 => 69,  168 => 66,  166 => 65,  162 => 64,  157 => 62,  151 => 61,  148 => 60,  131 => 59,  100 => 31,  95 => 28,  87 => 25,  76 => 24,  71 => 22,  68 => 21,  64 => 20,  58 => 17,  47 => 9,  37 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("", "FrontasticCatwalkApiCoreBundle:App:dataObject.php.twig", "/var/www/frontastic/paas/catwalk/src/php/ApiCoreBundle/Resources/views/App/dataObject.php.twig");
    }
}
