# This should always be the last entry
frontend_nodes:
    resource: .
    prefix:   /
    type:     "frontastic"

frontastic_nextjs:
    resource: .
    prefix:   /
    type:     "frontastic-nextjs"
