<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GZHKBIF' shared service.

return $this->privates['.service_locator.GZHKBIF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'context' => ['services', 'Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\Context', 'getContextService.php', true],
], [
    'context' => 'Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\Context',
]);
