<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\AccountAddressesMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AccountAddressesMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\AccountAddressesMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AddressMapper'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AddressMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\AddressMapper())));
