<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\AggregationMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\AggregationMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\AggregationMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\Search\\SearchAggregationFactory'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\Search\\SearchAggregationFactory'] = new \Frontastic\Common\ShopwareBundle\Domain\ProductApi\Search\SearchAggregationFactory())));
