<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\SprykerBundle\Domain\Account\AccountHelper' shared service.

return $this->services['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\AccountHelper'] = new \Frontastic\Common\SprykerBundle\Domain\Account\AccountHelper(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextService'] ?? $this->getContextServiceService()), ($this->services['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\SessionService'] ?? ($this->services['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\SessionService'] = new \Frontastic\Common\SprykerBundle\Domain\Account\SessionService())));
