<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\AccountApiBundle\Domain\AccountApiFactory' shared service.

return $this->services['Frontastic\\Common\\AccountApiBundle\\Domain\\AccountApiFactory'] = new \Frontastic\Common\AccountApiBundle\Domain\AccountApiFactory($this, new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0), ($this->services['logger'] ?? $this->getLoggerService()));
