<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\SprykerBundle\Domain\Account\Mapper\AccountMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\AccountMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Account\Mapper\AccountMapper(($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\AddressMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\AddressMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Account\Mapper\AddressMapper())));
