<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\AppService' shared service.

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\AppService'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\AppService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Gateway\\AppGateway'] ?? $this->load('getAppGatewayService.php')), ($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\AppRepositoryService'] ?? $this->load('getAppRepositoryServiceService.php')));
