<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\TasticFieldHandler\BreadcrumbFieldHandler' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\TasticFieldHandler\\BreadcrumbFieldHandler'] = new \Frontastic\Catwalk\FrontendBundle\Domain\TasticFieldHandler\BreadcrumbFieldHandler(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\NodeService'] ?? $this->load('getNodeServiceService.php')));
