<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ProductApiBundle\Domain\ProductApi\Commercetools\ClientFactory' shared service.

return $this->services['Frontastic\\Common\\ProductApiBundle\\Domain\\ProductApi\\Commercetools\\ClientFactory'] = new \Frontastic\Common\ProductApiBundle\Domain\ProductApi\Commercetools\ClientFactory(new \Doctrine\Common\Cache\ApcuCache(), ($this->services['Frontastic\\Common\\HttpClient'] ?? $this->load('getHttpClientService.php')));
