<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cache.app.simple' shared service.

@trigger_error('The "Psr\\SimpleCache\\CacheInterface" / "cache.app.simple" service is deprecated since Symfony 4.3. Use "Symfony\\Contracts\\Cache\\CacheInterface" / "cache.app" instead.', E_USER_DEPRECATED);

return $this->privates['cache.app.simple'] = new \Symfony\Component\Cache\Psr16Cache(($this->services['cache.app'] ?? $this->load('getCache_AppService.php')));
