<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\ProjectConfigApi\DataMapper\CountriesMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProjectConfigApi\\DataMapper\\CountriesMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\ProjectConfigApi\DataMapper\CountriesMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProjectConfigApi\\DataMapper\\CountryMapper'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProjectConfigApi\\DataMapper\\CountryMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\ProjectConfigApi\DataMapper\CountryMapper())));
