<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\CartApi\DataMapper\CartMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\CartApi\\DataMapper\\CartMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\CartApi\DataMapper\CartMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AddressMapper'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AddressMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\AddressMapper())), ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\CartApi\\DataMapper\\LineItemsMapper'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\CartApi\\DataMapper\\LineItemsMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\CartApi\DataMapper\LineItemsMapper())));
