<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\CommerceTools\ClientFactory' shared autowired service.

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\CommerceTools\\ClientFactory'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\CommerceTools\ClientFactory(($this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\Project'] ?? $this->getProjectService()), ($this->services['Frontastic\\Common\\ProductApiBundle\\Domain\\ProductApi\\Commercetools\\ClientFactory'] ?? $this->load('getClientFactory2Service.php')));
