<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\ContextInContainerDeprecationProvider' shared service.

@trigger_error('Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextInContainerDeprecationProvider is only used to enforce deprecation of Context from Container. User ContextService instead!', E_USER_DEPRECATED);

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextInContainerDeprecationProvider'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\ContextInContainerDeprecationProvider(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextService'] ?? $this->getContextServiceService()));
