<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\Context' shared service.

@trigger_error('Retrieving the Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\Context from the Container is deprecated. Retrieve ContextService instead!', E_USER_DEPRECATED);

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\Context'] = ($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextInContainerDeprecationProvider'] ?? $this->load('getContextInContainerDeprecationProviderService.php'))->provideContext();
