<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\AccountApiBundle\Command\CreateAccountCommand' shared service.

return $this->services['Frontastic\\Common\\AccountApiBundle\\Command\\CreateAccountCommand'] = new \Frontastic\Common\AccountApiBundle\Command\CreateAccountCommand();
