<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ShopwareBundle\Domain\ClientFactory' shared service.

return $this->services['Frontastic\\Common\\ShopwareBundle\\Domain\\ClientFactory'] = new \Frontastic\Common\ShopwareBundle\Domain\ClientFactory(($this->services['Frontastic\\Common\\HttpClient'] ?? $this->load('getHttpClientService.php')));
