<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\RulerZ\Operator\CategoriesContain' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\RulerZ\\Operator\\CategoriesContain'] = new \Frontastic\Catwalk\FrontendBundle\RulerZ\Operator\CategoriesContain(($this->services['frontastic.catwalk.product_api'] ?? $this->load('getFrontastic_Catwalk_ProductApiService.php')), ($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextService'] ?? $this->getContextServiceService()));
