<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\CustomerCreateRequestDataMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\CustomerCreateRequestDataMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\CustomerCreateRequestDataMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AddressCreateRequestDataMapper'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\AccountApi\\DataMapper\\AddressCreateRequestDataMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\AccountApi\DataMapper\AddressCreateRequestDataMapper())));
