<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Domnikl\Statsd\Client' shared service.

return $this->services['Domnikl\\Statsd\\Client'] = new \Domnikl\Statsd\Client(new \Domnikl\Statsd\Connection\UdpSocket('127.0.0.1', 8125));
