<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.error_listener' shared service.

$a = new \Symfony\Bridge\Monolog\Logger('console');
$a->pushProcessor(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Monolog\\FrontasticLogProcessor'] ?? $this->getFrontasticLogProcessorService()));
$a->pushHandler(($this->privates['monolog.handler.filter_for_errors'] ?? $this->getMonolog_Handler_FilterForErrorsService()));

return $this->privates['console.error_listener'] = new \Symfony\Component\Console\EventListener\ErrorListener($a);
