<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\SapCommerceCloudBundle\Domain\Locale\DefaultSapLocaleCreatorFactory' shared service.

return $this->services['Frontastic\\Common\\SapCommerceCloudBundle\\Domain\\Locale\\DefaultSapLocaleCreatorFactory'] = new \Frontastic\Common\SapCommerceCloudBundle\Domain\Locale\DefaultSapLocaleCreatorFactory(($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')));
