<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ProjectApiBundle\Domain\DefaultProjectApiFactory' shared service.

return $this->services['Frontastic\\Common\\ProjectApiBundle\\Domain\\DefaultProjectApiFactory'] = new \Frontastic\Common\ProjectApiBundle\Domain\DefaultProjectApiFactory(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ProductSearchApiFactoryDecorator'] ?? $this->load('getProductSearchApiFactoryDecoratorService.php')));
