<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ContentApiBundle\Domain\DefaultContentApiFactory' shared service.

return $this->services['Frontastic\\Common\\ContentApiBundle\\Domain\\DefaultContentApiFactory'] = new \Frontastic\Common\ContentApiBundle\Domain\DefaultContentApiFactory($this, new \Doctrine\Common\Cache\ApcuCache(), ($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')), ($this->services['Contentful\\RichText\\Renderer'] ?? ($this->services['Contentful\\RichText\\Renderer'] = new \Contentful\RichText\Renderer())), false, new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));
