<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\EnabledFacetService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\EnabledFacetService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\EnabledFacetService(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\FacetService'] ?? $this->load('getFacetServiceService.php')), ($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')));
