<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\EventListener\ErrorHandler' shared autowired service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\EventListener\\ErrorHandler'] = new \Frontastic\Catwalk\FrontendBundle\EventListener\ErrorHandler(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextService'] ?? $this->getContextServiceService()), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\EventListener\\ErrorHandler\\ErrorNodeRenderer'] ?? $this->load('getErrorNodeRendererService.php')));
