<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\EventListener\ErrorHandler\ErrorNodeRenderer' shared autowired service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\EventListener\\ErrorHandler\\ErrorNodeRenderer'] = new \Frontastic\Catwalk\FrontendBundle\EventListener\ErrorHandler\ErrorNodeRenderer(($this->services['twig'] ?? $this->load('getTwigService.php')), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\MasterService'] ?? $this->load('getMasterServiceService.php')), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\NodeService'] ?? $this->load('getNodeServiceService.php')), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\PageService'] ?? $this->load('getPageServiceService.php')), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\ViewDataProvider'] ?? $this->load('getViewDataProviderService.php')));
