<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ReplicatorBundle\Domain\EndpointService' shared service.

$this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\EndpointService'] = $instance = new \Frontastic\Common\ReplicatorBundle\Domain\EndpointService();

$instance->addReplicationTarget('nodes', ($this->services['frontastic.catwalk.frontend_bundle.domain.node.replication_target'] ?? $this->load('getFrontastic_Catwalk_FrontendBundle_Domain_Node_ReplicationTargetService.php')));
$instance->addReplicationTarget('pages', ($this->services['frontastic.catwalk.frontend_bundle.domain.page.replication_target'] ?? $this->load('getFrontastic_Catwalk_FrontendBundle_Domain_Page_ReplicationTargetService.php')));
$instance->addReplicationTarget('page-matcher', ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\MasterService'] ?? $this->load('getMasterServiceService.php')));
$instance->addReplicationTarget('facets', ($this->services['frontastic.catwalk.frontend_bundle.domain.facet.replication_target'] ?? $this->load('getFrontastic_Catwalk_FrontendBundle_Domain_Facet_ReplicationTargetService.php')));
$instance->addReplicationTarget('redirects', ($this->services['frontastic.catwalk.frontend_bundle.domain.redirect.replication_target'] ?? $this->load('getFrontastic_Catwalk_FrontendBundle_Domain_Redirect_ReplicationTargetService.php')));
$instance->addReplicationTarget('schemas', ($this->services['frontastic.catwalk.frontend_bundle.domain.schema.replication_target'] ?? $this->load('getFrontastic_Catwalk_FrontendBundle_Domain_Schema_ReplicationTargetService.php')));
$instance->addReplicationTarget('project_configurations', ($this->services['frontastic.catwalk.frontend_bundle.domain.project_configuration.replication_target'] ?? $this->load('getFrontastic_Catwalk_FrontendBundle_Domain_ProjectConfiguration_ReplicationTargetService.php')));
$instance->addReplicationTarget('tastics', ($this->services['frontastic.catwalk.api_core_bundle.domain.tastic_target'] ?? $this->load('getFrontastic_Catwalk_ApiCoreBundle_Domain_TasticTargetService.php')));
$instance->addReplicationTarget('apps', ($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\AppService'] ?? $this->load('getAppServiceService.php')));
$instance->addReplicationTarget('app_data', ($this->services['frontastic.catwalk.api_core_bundle.domain.app_data_target'] ?? $this->load('getFrontastic_Catwalk_ApiCoreBundle_Domain_AppDataTargetService.php')));

return $instance;
