<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\FindologicBundle\Domain\FindologicClientFactory' shared service.

return $this->services['Frontastic\\Common\\FindologicBundle\\Domain\\FindologicClientFactory'] = new \Frontastic\Common\FindologicBundle\Domain\FindologicClientFactory(($this->services['Frontastic\\Common\\HttpClient'] ?? $this->load('getHttpClientService.php')), ($this->services['Frontastic\\Common\\CoreBundle\\Domain\\RequestProvider'] ?? $this->load('getRequestProviderService.php')));
