<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'frontastic.catwalk.cart_api' shared service.

return $this->services['frontastic.catwalk.cart_api'] = ($this->services['Frontastic\\Common\\CartApiBundle\\Domain\\CartApiFactory'] ?? $this->load('getCartApiFactoryService.php'))->factor(($this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\Project'] ?? $this->getProjectService()));
