<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Twig\FrontasticNodeViewFallbackTemplateGuesser' shared autowired service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\FrontasticNodeViewFallbackTemplateGuesser'] = new \Frontastic\Catwalk\FrontendBundle\Twig\FrontasticNodeViewFallbackTemplateGuesser(($this->services['logger'] ?? $this->getLoggerService()), new \QafooLabs\Bundle\NoFrameworkBundle\View\SymfonyConventionsTemplateGuesser(new \QafooLabs\Bundle\NoFrameworkBundle\View\BundleLocation(($this->services['kernel'] ?? $this->get('kernel', 1))), new \QafooLabs\Bundle\NoFrameworkBundle\Controller\QafooControllerNameParser(($this->privates['.legacy_controller_name_converter'] ?? ($this->privates['.legacy_controller_name_converter'] = new \Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser(($this->services['kernel'] ?? $this->get('kernel', 1)), false))), $this)), ($this->services['twig'] ?? $this->load('getTwigService.php')));
