<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'frontastic.catwalk.api_core_bundle.domain.tastic_target' shared service.

return $this->services['frontastic.catwalk.api_core_bundle.domain.tastic_target'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\EnvironmentReplicationFilter(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\TasticService'] ?? $this->load('getTasticServiceService.php')), 'production');
