<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\FacetService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\FacetService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\FacetService(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Gateway\\FacetGateway'] ?? $this->load('getFacetGatewayService.php')));
