<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\FeatureFlagService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\FeatureFlagService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\FeatureFlagService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\AppRepositoryService'] ?? $this->load('getAppRepositoryServiceService.php'))->getRepository('FeatureFlag'));
