<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'frontastic.catwalk.content_api' shared service.

return $this->services['frontastic.catwalk.content_api'] = ($this->services['Frontastic\\Common\\ContentApiBundle\\Domain\\DefaultContentApiFactory'] ?? $this->load('getDefaultContentApiFactoryService.php'))->factor(($this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\Project'] ?? $this->getProjectService()));
