<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\SprykerBundle\Domain\Cart\Mapper\GuestCartMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\GuestCartMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Cart\Mapper\GuestCartMapper(($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\LineItemMapper'] ?? $this->load('getLineItemMapperService.php')));
