<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\CoreBundle\EventListener\JsonExceptionListener' shared service.

return $this->services['Frontastic\\Common\\CoreBundle\\EventListener\\JsonExceptionListener'] = new \Frontastic\Common\CoreBundle\EventListener\JsonExceptionListener(false);
