<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\JsonSerializer' shared service.

return $this->services['Frontastic\\Common\\JsonSerializer'] = new \Frontastic\Common\JsonSerializer([0 => 'accessToken', 1 => 'apiKey', 2 => 'apiSecret', 3 => 'apiToken', 4 => 'clientId', 5 => 'clientSecret', 6 => 'newPassword', 7 => 'password', 8 => 'passwordHash', 9 => 'previewToken', 10 => 'secret', 11 => 'token', 12 => 'metaData'], new RewindableGenerator(function () {
    yield 0 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Routing\\UrlGenerator'] ?? $this->load('getUrlGeneratorService.php'));
}, 1));
