<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Routing\Loader' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Routing\\Loader'] = new \Frontastic\Catwalk\FrontendBundle\Routing\Loader(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RouteService'] ?? $this->load('getRouteServiceService.php')));
