<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\SprykerBundle\Domain\Locale\LocaleCreatorFactory' shared service.

return $this->services['Frontastic\\Common\\SprykerBundle\\Domain\\Locale\\LocaleCreatorFactory'] = new \Frontastic\Common\SprykerBundle\Domain\Locale\DefaultLocaleCreatorFactory(($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')));
