<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ShopwareBundle\Domain\Locale\LocaleCreatorFactory' shared service.

return $this->services['Frontastic\\Common\\ShopwareBundle\\Domain\\Locale\\LocaleCreatorFactory'] = new \Frontastic\Common\ShopwareBundle\Domain\Locale\DefaultLocaleCreatorFactory(($this->services['Frontastic\\Common\\ShopwareBundle\\Domain\\ProjectConfigApi\\ShopwareProjectConfigApiFactory'] ?? $this->load('getShopwareProjectConfigApiFactoryService.php')));
