<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\CartApiBundle\Domain\CartApi\Commercetools\Mapper' shared service.

return $this->services['Frontastic\\Common\\CartApiBundle\\Domain\\CartApi\\Commercetools\\Mapper'] = new \Frontastic\Common\CartApiBundle\Domain\CartApi\Commercetools\Mapper(($this->services['Frontastic\\Common\\AccountApiBundle\\Domain\\AccountApi\\Commercetools\\Mapper'] ?? ($this->services['Frontastic\\Common\\AccountApiBundle\\Domain\\AccountApi\\Commercetools\\Mapper'] = new \Frontastic\Common\AccountApiBundle\Domain\AccountApi\Commercetools\Mapper())), ($this->services['Frontastic\\Common\\ProductApiBundle\\Domain\\ProductApi\\Commercetools\\Mapper'] ?? ($this->services['Frontastic\\Common\\ProductApiBundle\\Domain\\ProductApi\\Commercetools\\Mapper'] = new \Frontastic\Common\ProductApiBundle\Domain\ProductApi\Commercetools\Mapper())));
