<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.logger.security' shared service.

$this->privates['monolog.logger.security'] = $instance = new \Symfony\Bridge\Monolog\Logger('security');

$instance->pushProcessor(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Monolog\\FrontasticLogProcessor'] ?? $this->getFrontasticLogProcessorService()));
$instance->pushHandler(($this->privates['monolog.handler.filter_for_errors'] ?? $this->getMonolog_Handler_FilterForErrorsService()));

return $instance;
