<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\MasterService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\MasterService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\MasterService(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Gateway\\MasterPageMatcherRulesGateway'] ?? $this->load('getMasterPageMatcherRulesGatewayService.php')), ($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\TasticService'] ?? $this->load('getTasticServiceService.php')), ($this->privates['rulerz'] ?? $this->load('getRulerzService.php')));
