<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\SprykerBundle\Domain\MapperResolver' shared service.

return $this->services['Frontastic\\Common\\SprykerBundle\\Domain\\MapperResolver'] = new \Frontastic\Common\SprykerBundle\Domain\MapperResolver(new RewindableGenerator(function () {
    yield 0 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\AccountMapper'] ?? $this->load('getAccountMapper2Service.php'));
    yield 1 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\AddressMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\AddressMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Account\Mapper\AddressMapper()));
    yield 2 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\SprykerSalutationMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\SprykerSalutationMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Account\Mapper\SprykerSalutationMapper()));
    yield 3 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\TokenMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Account\\Mapper\\TokenMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Account\Mapper\TokenMapper()));
    yield 4 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\CheckoutMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\CheckoutMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Cart\Mapper\CheckoutMapper()));
    yield 5 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\CustomerCartMapper'] ?? $this->load('getCustomerCartMapperService.php'));
    yield 6 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\GuestCartMapper'] ?? $this->load('getGuestCartMapperService.php'));
    yield 7 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\LineItemMapper'] ?? $this->load('getLineItemMapperService.php'));
    yield 8 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\OrderMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Cart\\Mapper\\OrderMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Cart\Mapper\OrderMapper()));
    yield 9 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\CategoriesMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\CategoriesMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Product\Mapper\CategoriesMapper()));
    yield 10 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\ProductConcreteMapper'] ?? $this->load('getProductConcreteMapperService.php'));
    yield 11 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\ProductMapper'] ?? $this->load('getProductMapper2Service.php'));
    yield 12 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\ProductResultMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\ProductResultMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Product\Mapper\ProductResultMapper()));
    yield 13 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\VariantMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\VariantMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Product\Mapper\VariantMapper()));
    yield 14 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\VariantMapperExtended'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\VariantMapperExtended'] = new \Frontastic\Common\SprykerBundle\Domain\Product\Mapper\VariantMapperExtended()));
    yield 15 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Project\\Mapper\\ProductSearchableAttributesMapper'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Project\\Mapper\\ProductSearchableAttributesMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Project\Mapper\ProductSearchableAttributesMapper()));
    yield 16 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Wishlist\\Mapper\\LineItemMapper'] ?? $this->load('getLineItemMapper2Service.php'));
    yield 17 => ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Wishlist\\Mapper\\WishlistMapper'] ?? $this->load('getWishlistMapperService.php'));
}, 18));
