<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\NodeService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\NodeService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\NodeService(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Gateway\\NodeGateway'] ?? $this->load('getNodeGatewayService.php')), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RouteService'] ?? $this->load('getRouteServiceService.php')));
