<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\HttpClient\Options' shared service.

return $this->services['Frontastic\\Common\\HttpClient\\Options'] = new \Frontastic\Common\HttpClient\Options(['timeout' => $this->getEnv('http_client_timeout')]);
