<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\ProductApiFactoryDecorator' shared service.

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ProductApiFactoryDecorator'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\ProductApiFactoryDecorator(($this->services['Frontastic\\Common\\ProductApiBundle\\Domain\\DefaultProductApiFactory'] ?? $this->load('getDefaultProductApiFactoryService.php')), ($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')), false);
