<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\StreamHandler\ProductList' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\ProductList'] = new \Frontastic\Catwalk\FrontendBundle\Domain\StreamHandler\ProductList(($this->services['frontastic.catwalk.product_search_api'] ?? $this->load('getFrontastic_Catwalk_ProductSearchApiService.php')));
