<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\SprykerBundle\Domain\Product\Mapper\ProductConcreteMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\ProductConcreteMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Product\Mapper\ProductConcreteMapper(($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\VariantMapperExtended'] ?? ($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Product\\Mapper\\VariantMapperExtended'] = new \Frontastic\Common\SprykerBundle\Domain\Product\Mapper\VariantMapperExtended())), new \Frontastic\Common\SprykerBundle\Domain\Product\Expander\Nested\NestedAttributeValueTransformExpander(), new \Frontastic\Common\SprykerBundle\Domain\Product\Expander\Nested\NestedVariantAttributeUrlExpander(new \Frontastic\Common\SprykerBundle\Domain\Route\Service\VariantUrlEncoder(new \Frontastic\Common\SprykerBundle\Domain\Product\SprykerSlugger())));
