<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\StreamHandler\Product' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\Product'] = new \Frontastic\Catwalk\FrontendBundle\Domain\StreamHandler\Product(($this->services['frontastic.catwalk.product_api'] ?? $this->load('getFrontastic_Catwalk_ProductApiService.php')));
