<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\PageService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\PageService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\PageService(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Gateway\\PageGateway'] ?? $this->load('getPageGatewayService.php')), ($this->privates['rulerz'] ?? $this->load('getRulerzService.php')));
