<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\ProductResultMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\ProductResultMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\ProductResultMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\ProductMapper'] ?? $this->load('getProductMapperService.php')), ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\AggregationMapper'] ?? $this->load('getAggregationMapperService.php')));
