<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\ProductSearchApiFactoryDecorator' shared service.

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ProductSearchApiFactoryDecorator'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\ProductSearchApiFactoryDecorator(new \Frontastic\Common\ProductSearchApiBundle\Domain\DefaultProductSearchApiFactory($this, ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\EnabledFacetService'] ?? $this->load('getEnabledFacetServiceService.php')), ($this->services['logger'] ?? $this->getLoggerService()), new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0), new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0)), ($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')), false);
