<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\ProductMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\ProductMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\ProductMapper(($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\ProductVariantMapper'] ?? ($this->privates['Frontastic\\Common\\ShopwareBundle\\Domain\\ProductApi\\DataMapper\\ProductVariantMapper'] = new \Frontastic\Common\ShopwareBundle\Domain\ProductApi\DataMapper\ProductVariantMapper())));
