<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\PageImpressionRecorder' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\PageImpressionRecorder'] = new \Frontastic\Catwalk\FrontendBundle\Domain\PageImpressionRecorder(($this->services['Domnikl\\Statsd\\Client'] ?? $this->load('getClientService.php')));
