<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'qafoo_labs_noframework.controller_utils' shared service.

return $this->services['qafoo_labs_noframework.controller_utils'] = new \QafooLabs\Bundle\NoFrameworkBundle\Controller\ControllerUtils($this);
