<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'qafoo_labs_noframework.redirect_listener' shared service.

return $this->privates['qafoo_labs_noframework.redirect_listener'] = new \QafooLabs\Bundle\NoFrameworkBundle\EventListener\RedirectListener(($this->services['router'] ?? $this->getRouterService()));
