<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\RouteService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RouteService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\RouteService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\CustomerService'] ?? ($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\CustomerService'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\CustomerService((\dirname(__DIR__, 5).'/'.$this->getEnv('string:default:frontastic_default_project_file:frontastic_project_file'))))), $this->targetDir.'');
