<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\CartApiBundle\Domain\OrderIdGenerator\Random' shared service.

return $this->services['Frontastic\\Common\\CartApiBundle\\Domain\\OrderIdGenerator\\Random'] = new \Frontastic\Common\CartApiBundle\Domain\OrderIdGenerator\Random();
