<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\RedirectService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RedirectService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\RedirectService(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Gateway\\RedirectGateway'] ?? $this->load('getRedirectGatewayService.php')), ($this->services['router'] ?? $this->getRouterService()));
