<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\RenderService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RenderService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\RenderService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\ContextService'] ?? $this->getContextServiceService()), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RenderService\\ResponseDecorator'] ?? ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RenderService\\ResponseDecorator'] = new \Frontastic\Catwalk\FrontendBundle\Domain\RenderService\ResponseDecorator())), new \Frontastic\Common\HttpClient\StatsD('catwalk.node', ($this->services['Domnikl\\Statsd\\Client'] ?? $this->load('getClientService.php')), ($this->services['Frontastic\\Common\\HttpClient'] ?? $this->load('getHttpClientService.php'))), 'http://localhost:8000', ($this->services['Frontastic\\Common\\JsonSerializer'] ?? $this->load('getJsonSerializerService.php')), ($this->services['logger'] ?? $this->getLoggerService()));
