<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ReplicatorBundle\Domain\RequestVerifier' shared service.

return $this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\RequestVerifier'] = new \Frontastic\Common\ReplicatorBundle\Domain\RequestVerifier();
