<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'rulerz.command.cache_clear' shared service.

return $this->services['rulerz.command.cache_clear'] = new \KPhoen\RulerZBundle\Command\CacheClearCommand();
