<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Twig\RenderExtension' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\RenderExtension'] = new \Frontastic\Catwalk\FrontendBundle\Twig\RenderExtension(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\RenderService'] ?? $this->load('getRenderServiceService.php')));
