<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\CoreBundle\Domain\RequestProvider' shared service.

return $this->services['Frontastic\\Common\\CoreBundle\\Domain\\RequestProvider'] = new \Frontastic\Common\CoreBundle\Domain\RequestProvider(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
