<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'rulerz.validator.unique.rule_validator' shared service.

return $this->privates['rulerz.validator.unique.rule_validator'] = new \Symfony\Bridge\RulerZ\Validator\Constraints\RuleValidator(new \RulerZ\Parser\Parser());
