<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.guard.main' shared service.

return $this->privates['security.authentication.provider.guard.main'] = new \Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider(new RewindableGenerator(function () {
    yield 0 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Security\\Authenticator'] ?? $this->load('getAuthenticatorService.php'));
}, 1), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Security\\AccountProvider'] ?? $this->load('getAccountProviderService.php')), 'main', new \Symfony\Component\Security\Core\User\UserChecker(), ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')));
