<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\SprykerBundle\Domain\SprykerClientFactory' shared service.

return $this->services['Frontastic\\Common\\SprykerBundle\\Domain\\SprykerClientFactory'] = new \Frontastic\Common\SprykerBundle\Domain\SprykerClientFactory(($this->services['Frontastic\\Common\\HttpClient'] ?? $this->load('getHttpClientService.php')), new \Frontastic\Common\SprykerBundle\Domain\Exception\ExceptionFactory());
