<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'session' shared service.

return $this->services['session'] = new \Symfony\Component\HttpFoundation\Session\Session(new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage($this->parameters['session.storage.options'], new \Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler('mysql:dbname='.$this->getEnv('string:database_name').'; host='.$this->getEnv('string:database_host').'; port='.$this->getEnv('string:database_port'), ['db_table' => 'http_session', 'db_username' => $this->getEnv('database_user'), 'db_password' => $this->getEnv('database_password'), 'lock_mode' => 0]), new \Symfony\Component\HttpFoundation\Session\Storage\MetadataBag('_sf2_meta', 0)));
