<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\SitemapService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\SitemapService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\SitemapService(new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));
