<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Common\ShopwareBundle\Domain\ProjectConfigApi\ShopwareProjectConfigApiFactory' shared service.

return $this->services['Frontastic\\Common\\ShopwareBundle\\Domain\\ProjectConfigApi\\ShopwareProjectConfigApiFactory'] = new \Frontastic\Common\ShopwareBundle\Domain\ProjectConfigApi\ShopwareProjectConfigApiFactory(($this->privates['cache.app.simple'] ?? $this->load('getCache_App_SimpleService.php')), ($this->services['Frontastic\\Common\\ShopwareBundle\\Domain\\DataMapper\\DataMapperResolver'] ?? $this->load('getDataMapperResolverService.php')), false);
