<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'swiftmailer.mailer.default.transport.real' shared service.

return $this->services['swiftmailer.mailer.default.transport.real'] = \Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerTransportFactory::createTransport(['transport' => 'smtp', 'url' => NULL, 'username' => $this->getEnv('smtp_user'), 'password' => $this->getEnv('smtp_password'), 'host' => $this->getEnv('smtp_host'), 'port' => $this->getEnv('smtp_port'), 'timeout' => 30, 'source_ip' => NULL, 'local_domain' => NULL, 'encryption' => $this->getEnv('smtp_encryption'), 'auth_mode' => NULL, 'command' => '/usr/sbin/sendmail -t -i ', 'stream_options' => []], ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()), ($this->privates['swiftmailer.mailer.default.transport.eventdispatcher'] ?? ($this->privates['swiftmailer.mailer.default.transport.eventdispatcher'] = new \Swift_Events_SimpleEventDispatcher())));
