<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\DevVmBundle\Controller\SyncController' shared service.

return $this->services['Frontastic\\Catwalk\\DevVmBundle\\Controller\\SyncController'] = new \Frontastic\Catwalk\DevVmBundle\Controller\SyncController(($this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\RequestVerifier'] ?? ($this->services['Frontastic\\Common\\ReplicatorBundle\\Domain\\RequestVerifier'] = new \Frontastic\Common\ReplicatorBundle\Domain\RequestVerifier())), $this->getEnv('secret'), (\dirname(__DIR__, 5).'/public/assets'));
