<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\StreamService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\StreamService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\TasticService'] ?? $this->load('getTasticServiceService.php')), ($this->services['logger'] ?? $this->getLoggerService()), new RewindableGenerator(function () {
    yield 0 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\ProductList'] ?? $this->load('getProductListService.php'));
    yield 1 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\Product'] ?? $this->load('getProductService.php'));
    yield 2 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\ContentList'] ?? $this->load('getContentListService.php'));
    yield 3 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\Content'] ?? $this->load('getContentService.php'));
    yield 4 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\AccountAddresses'] ?? $this->load('getAccountAddressesService.php'));
    yield 5 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\AccountOrders'] ?? $this->load('getAccountOrdersService.php'));
    yield 6 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\AccountWishlists'] ?? $this->load('getAccountWishlistsService.php'));
    yield 7 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamHandler\\Order'] ?? $this->load('getOrderService.php'));
}, 8), new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0), false);
