<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\TasticFieldService' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\TasticFieldService'] = new \Frontastic\Catwalk\FrontendBundle\Domain\TasticFieldService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\TasticService'] ?? $this->load('getTasticServiceService.php')), new RewindableGenerator(function () {
    yield 0 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\TasticFieldHandler\\TreeFieldHandler'] ?? $this->load('getTreeFieldHandlerService.php'));
    yield 1 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\TasticFieldHandler\\BreadcrumbFieldHandler'] ?? $this->load('getBreadcrumbFieldHandlerService.php'));
    yield 2 => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\TasticFieldHandler\\AccountWishlistsFieldHandler'] ?? $this->load('getAccountWishlistsFieldHandlerService.php'));
}, 3));
