<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.template_cache_warmer' shared service.

return $this->privates['twig.template_cache_warmer'] = new \Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer(($this->privates['.service_locator.o9nGMXB'] ?? $this->load('get_ServiceLocator_O9nGMXBService.php'))->withContext('twig.template_cache_warmer', $this), new \Symfony\Bundle\TwigBundle\TemplateIterator(($this->services['kernel'] ?? $this->get('kernel', 1)), \dirname(__DIR__, 5), [(\dirname(__DIR__, 5).'/templates/') => 'FrontasticCatwalkFrontendBundle', (\dirname(__DIR__, 5).'/src/php/../../src/php/FrontendBundle/Resources/views/') => 'FrontasticCatwalkFrontendBundle', (\dirname(__DIR__, 5).'/templates/Tastic/') => 'Tastic', (\dirname(__DIR__, 5).'/src/php/../../src/php/TwigTasticBundle/Resources/views/') => 'Tastic', (\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Email') => 'email', (\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form') => NULL], (\dirname(__DIR__, 5).'/templates')));
