<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\ApiCoreBundle\Domain\TasticService' shared service.

return $this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Domain\\TasticService'] = new \Frontastic\Catwalk\ApiCoreBundle\Domain\TasticService(($this->services['Frontastic\\Catwalk\\ApiCoreBundle\\Gateway\\TasticGateway'] ?? $this->load('getTasticGatewayService.php')), \dirname(__DIR__, 5), 'prod');
