<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'twig' shared service.

$a = new \Symfony\Bundle\TwigBundle\Loader\FilesystemLoader(($this->privates['templating.locator'] ?? $this->load('getTemplating_LocatorService.php')), ($this->privates['templating.name_parser'] ?? $this->load('getTemplating_NameParserService.php')), \dirname(__DIR__, 5));
$a->addPath((\dirname(__DIR__, 5).'/templates/'), 'FrontasticCatwalkFrontendBundle');
$a->addPath((\dirname(__DIR__, 5).'/src/php/../../src/php/FrontendBundle/Resources/views/'), 'FrontasticCatwalkFrontendBundle');
$a->addPath((\dirname(__DIR__, 5).'/templates/Tastic/'), 'Tastic');
$a->addPath((\dirname(__DIR__, 5).'/src/php/../../src/php/TwigTasticBundle/Resources/views/'), 'Tastic');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/views'), 'Framework');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/views'), '!Framework');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Resources/views'), 'Twig');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Resources/views'), '!Twig');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/views'), 'Security');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Resources/views'), '!Security');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/swiftmailer-bundle/Resources/views'), 'Swiftmailer');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/swiftmailer-bundle/Resources/views'), '!Swiftmailer');
$a->addPath((\dirname(__DIR__, 5).'/vendor/doctrine/doctrine-bundle/Resources/views'), 'Doctrine');
$a->addPath((\dirname(__DIR__, 5).'/vendor/doctrine/doctrine-bundle/Resources/views'), '!Doctrine');
$a->addPath((\dirname(__DIR__, 5).'/src/php/FrontendBundle/Resources/views'), 'FrontasticCatwalkFrontend');
$a->addPath((\dirname(__DIR__, 5).'/src/php/FrontendBundle/Resources/views'), '!FrontasticCatwalkFrontend');
$a->addPath((\dirname(__DIR__, 5).'/src/php/ApiCoreBundle/Resources/views'), 'FrontasticCatwalkApiCore');
$a->addPath((\dirname(__DIR__, 5).'/src/php/ApiCoreBundle/Resources/views'), '!FrontasticCatwalkApiCore');
$a->addPath((\dirname(__DIR__, 5).'/templates'));
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Email'), 'email');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Email'), '!email');
$a->addPath((\dirname(__DIR__, 5).'/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form'));

$this->services['twig'] = $instance = new \Twig\Environment($a, ['debug' => false, 'strict_variables' => false, 'autoescape' => 'name', 'cache' => ($this->targetDir.''.'/twig'), 'charset' => 'UTF-8']);

$b = ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
$c = new \Symfony\Bridge\Twig\AppVariable();
$c->setEnvironment('prod');
$c->setDebug(false);
if ($this->has('security.token_storage')) {
    $c->setTokenStorage(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()));
}
if ($this->has('request_stack')) {
    $c->setRequestStack($b);
}

$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CsrfExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\TranslationExtension(($this->services['translator'] ?? ($this->services['translator'] = new \Symfony\Component\Translation\IdentityTranslator()))));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\AssetExtension(new \Symfony\Component\Asset\Packages(new \Symfony\Component\Asset\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy(), new \Symfony\Component\Asset\Context\RequestStackContext($b, '', false)), [])));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CodeExtension(($this->privates['debug.file_link_formatter'] ?? ($this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), \dirname(__DIR__, 5), 'UTF-8'));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\RoutingExtension(($this->services['router'] ?? $this->getRouterService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\YamlExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\StopwatchExtension(($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))), false));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\ExpressionExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpKernelExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpFoundationExtension(new \Symfony\Component\HttpFoundation\UrlHelper($b, ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()))));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\FormExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\LogoutUrlExtension(($this->privates['security.logout_url_generator'] ?? $this->getSecurity_LogoutUrlGeneratorService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\SecurityExtension(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService())));
$instance->addExtension(new \Doctrine\Bundle\DoctrineBundle\Twig\DoctrineExtension());
$instance->addExtension(($this->services['Aptoma\\Twig\\Extension\\MarkdownExtension'] ?? $this->load('getMarkdownExtensionService.php')));
$instance->addExtension(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\RenderExtension'] ?? $this->load('getRenderExtensionService.php')));
$instance->addExtension(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\ContextExtension'] ?? ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\ContextExtension'] = new \Frontastic\Catwalk\FrontendBundle\Twig\ContextExtension($this))));
$instance->addExtension(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\NodeExtension'] ?? $this->getNodeExtensionService()));
$instance->addExtension(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\AssetExtension'] ?? ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\AssetExtension'] = new \Frontastic\Catwalk\FrontendBundle\Twig\AssetExtension())));
$instance->addExtension(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Twig\\JsonExtension'] ?? $this->load('getJsonExtensionService.php')));
$instance->addGlobal('app', $c);
$instance->addRuntimeLoader(new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => ['privates', 'twig.runtime.security_csrf', 'getTwig_Runtime_SecurityCsrfService.php', true],
    'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => ['privates', 'twig.runtime.httpkernel', 'getTwig_Runtime_HttpkernelService.php', true],
    'Symfony\\Component\\Form\\FormRenderer' => ['privates', 'twig.form.renderer', 'getTwig_Form_RendererService.php', true],
], [
    'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => '?',
    'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => '?',
    'Symfony\\Component\\Form\\FormRenderer' => '?',
])));
(new \Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator('F j, Y H:i', '%d days', NULL, 0, '.', ','))->configure($instance);

return $instance;
