<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Routing\UrlGenerator' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Routing\\UrlGenerator'] = new \Frontastic\Catwalk\FrontendBundle\Routing\UrlGenerator(['Frontastic\\Common\\ProductApiBundle\\Domain\\Product' => ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Routing\\ObjectRouter\\ProductRouter'] ?? ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Routing\\ObjectRouter\\ProductRouter'] = new \Frontastic\Catwalk\FrontendBundle\Routing\ObjectRouter\ProductRouter($this)))]);
