<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Frontastic\Catwalk\FrontendBundle\Domain\ViewDataProvider' shared service.

return $this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\ViewDataProvider'] = new \Frontastic\Catwalk\FrontendBundle\Domain\ViewDataProvider(($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\StreamService'] ?? $this->load('getStreamServiceService.php')), ($this->services['Frontastic\\Catwalk\\FrontendBundle\\Domain\\TasticFieldService'] ?? $this->load('getTasticFieldServiceService.php')));
