<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Frontastic\Common\SprykerBundle\Domain\Wishlist\Mapper\WishlistMapper' shared autowired service.

return $this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Wishlist\\Mapper\\WishlistMapper'] = new \Frontastic\Common\SprykerBundle\Domain\Wishlist\Mapper\WishlistMapper(($this->privates['Frontastic\\Common\\SprykerBundle\\Domain\\Wishlist\\Mapper\\LineItemMapper'] ?? $this->load('getLineItemMapper2Service.php')));
