// This file is autogenerated – run `ant apidocs` to update it

import {
    Configuration as NextJsApiConfiguration,
} from '../'

export interface Configuration extends NextJsApiConfiguration {
     name?: string;
}
